# 
# Multiplier
#
#	a simple picoVersat program

# set R2 iterator 	
	ldi 4
	wrw R2

# set R3 with value 1 
	ldi 1
	wrw R3

# Fill the registers with 2 numbers
	ldi 0x4  
	wrw R0 
	ldi 0x9 
	wrw R1 
check0
	rdw R1
	and R3
	beqi dec
	ldi 0		
	add R0	
	rdw R0  
	shft -1
	wrw R0	
dec	
	rdw R1
	shft 1
	wrw R1
	rdw R2 	
	sub 1 
	beqi end
	wrw R2 
	ldi 0 
	beqi check0
	
#printing the values to the console with trap
end	wrw CPRT_BASE	
	wrw TRAP_BASE

